# -*- coding: utf-8 -*-
"""foodapp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LDC_Zwe76Fcjky0htyfFOKwHcAwLlzXc
"""

import random
class food_info:
  def __init__(self, foodID=None ,name=None,quantity=None,price=None,stock=None,discount=None):
    self.foodID = foodID
    self.name=name
    self.quantity =quantity 
    self.price=price
    self.discount=discount
    self.stock =stock
  def set_name(self,name):
    self.name =name
  def get_name(self):
    return(self.name)
  def set_quantity(self,quantity):
    self.quantity =quantity
  def get_quantity(self):
    return(self.quantity)
  def set_price(self,price):
    self.price =price
  def get_price(self):
    return(self.price)
  def set_discount(self,discount):
    self.discount =discount
  def get_discount(self):
    return(self.discount)
  def set_stock(self,stock):
    self.stock =stock
  def get_stock(self):
    return(self.stock)
  def __str__(self):
    return( f"Food ID : {self.foodID} \nFood Name : {self.name} \nFood Quantity :{self.quantity} \nFood price:{self.price} \nFood Discount: {self.discount}\nFood stock: {self.stock}")

class admin(food_info):
  foodlist=[] 
  def __init__(self):
    food_info.__init__(self,foodID=None,name=None,quantity=None,price=None,stock=None,discount=None)   
  def add_items(self):
    print("**Add required details to add food items in your list ***")
    foodID =int(random.randint(0,100))
    name= (input("\nEnter the name:"))
    quantity=(input("\nEnter the quantity(ml,pieces,gm):"))
    price=(input("\nEnter the price:"))
    discount=input("\nEnter the discount:")
    stock=input("\nEnter the total stock:")
    obj_admin =food_info(foodID,name ,quantity,price,discount,stock)
    admin.foodlist.append(obj_admin)
    print("\n\n*****food item added sucessfully*****")
    
  def view_items(self):
    print("\n\n***items are display below***")
    for food in admin.foodlist:
      print(food ,"\n")
  def search_items(self,foodID):
    print("\n\n****search items is display below ***")
    for food in (admin.foodlist):
      if food.foodID==foodID:
        print(food)
        break
      else:
        print("you have entered wrong id")
        break
  def remove_items(self,foodID):
    for food in (admin.foodlist):
      if food.foodID==foodID:
        admin.foodlist.remove(food)
        print("\n\n***Items removed sucessfullly***")
        break
      else:
        print("you have entered wrong id")
        break
  def update_items(self,foodID):
    print("\n\n***Enter details to edit item list **")
    for food in (admin.foodlist):
      if food.foodID==foodID:         
         name =input("\nenter the updated name")
         quantity=((input("\nenter the quantity:")))
         price=((input("\nenter the price:")))
         discount=(input("\nenter the discount:"))
         stock=input("\nenter the stock:")
         food.set_name(name)
         food.set_quantity(quantity)
         food.set_price(price) 
         food.set_discount(discount)  
         food.set_stock(stock)
         print("\n\n****Items list has been updated**")
         for food in admin.foodlist:
           print(food ,"\n")
      else:
        print("you have entered wrong id")

class user:
  def __init__(self,fullname=None,mobilenumber=None,email=None,address=None ,password=None):
    self.fullname=fullname
    self.mobilenumber=mobilenumber
    self.email =email
    self.address=address
    self.password =password
  def set_fullname(self,fullname):
      self.fullname =fullname
  def get_fullname(self):
      return(self.fullname)
  def set_mobilenumber(self,mobilenumber):
      self.mobilenumber =mobilenumber
  def get_mobilenumber(self):
      return(self.mobilenumber)
  def set_email(self,email):
      self.email =email
  def get_email(self):
      return(self.email)
  def set_address(self,address):
      self.address =address
  def get_address(self):
      return(self.address)
  def set_password(self,password):
      self.password =password
  def get_password(self):
      return(self.password)
  def __str__(self):
    return(f"User full name:{self.fullname}\nmobile number is {self.mobilenumber}\nemail:{self.email}\naddress is:{self.address}\npassword is :{self.password}")



class customer(user,admin):
  userlist=[]
  orderlist=[]
  displaylist=[]
  def __init__(self):
    user.__init__(self,fullname=None,mobilenumber=None,email=None,address=None ,password=None)
    self.admin =admin()
    self.user= user()
  def registration(self):
    print("\n\n***Enter the required details***")
    fullname=input("enter the full name : ")
    mobilenumber=int(input("enter the mobile number: "))
    email= input("enter the email: ")
    address=input("enter the full address: ")
    password =input("enter the your password: ")
    obj_user=user(fullname,mobilenumber,email,address,password)
    customer.userlist.append(obj_user)
    print("\n\n******** Registration sucessful & please proceed for login*****")
  def login(self,username,userpassword):
    for i in customer.userlist:
      if i.fullname ==username:
         if i.password == userpassword:
           print("\n**login sucessful***")
           break
         else:
           print("\n***wrong input , please enter again***")
           break
      else:
        print("\n***wrong input , please enter again***")

  def displayfooditems(self):
      print("\n\n**kindly choose items shown below*")
      customer.displaylist=[]
      index=0
      for food in (self.admin.foodlist):
         print(f"item number {index}  food name:{food.name}   food qty:{food.quantity}  food price:{food.price}")
         index=index+1
      n =1
      while (n==1):
          orderfood =int(input("\n\n*enter the item number"))
          selected =self.admin.foodlist[orderfood]
          customer.displaylist.append(selected)
          customer.orderlist.append(selected)
          m = int(input("\n**press 1 if want to add more else press 0** "))
          n=m
      print("\n****Ordered food **")
      for i in (customer.displaylist):
        print(f"Food name :{i.name} Food Qty: {i.quantity} Food price: {i.price}")
  def orderhistory(self):
    print("\n\n**Order history****")
    for i in (customer.orderlist):
        print(f"Food name :{i.name} Food Qty: {i.quantity} Food price: {i.price}")
  def updateprofile(self ,username,userpassword):
      for i in customer.userlist:
          if (i.fullname ==username) & (i.password == userpassword):
                fullname=input("enter the full name : ")
                mobilenumber=int(input("enter the mobile number: "))
                email= input("enter the email: ")
                address=input("enter the full address: ")
                password =input("enter the your password: ")
                i.set_fullname(fullname)
                i.set_mobilenumber(mobilenumber)
                i.set_email(email)
                i.set_address(address)
                i.set_password(password)
                print("\n\n*** Details has been updated*****")
          else:
             print("you have entered wrong id & password")
             break

class mainoperation(customer):
  def __init__(self):
    self.admin = admin()
    self.customer =customer()
  def execute(self,choice):
    print("\n\n***Running***")
    if choice==2:
      n=1
      while(n==1):
        adminoptions =int(input("enter 1 to add items: \nenter 2 to view items: \nenter 3 for edit items: \nenter 4 for removing items: \nenter 5 to search items \nenter 6 to update the item list"))
        n=1
        if adminoptions==1:
            self.admin.add_items()
        elif adminoptions==2:
            self.admin.view_items()
        elif adminoptions==3:
            foodID =int(input("\n ***enter the food ID"))
            self.admin.update_items(foodID)
        elif adminoptions==4:
            foodID =int(input("enter the food ID"))
            self.admin.remove_items(foodID) 
        elif adminoptions==5:
            foodID= int(input("enter the food ID"))
            self.admin.search_items(foodID)
        elif adminoptions==6:
            foodID= int(input("enter the food ID"))
            self.admin.update_items(foodID)
        n=int(input("if you want goto previous menu press 0 to continue as admin press 1"))
    elif choice ==1:
      useroptions=int(input("Press 1 for regisration : \nPress2 for login :  "))
      if useroptions==1:
        print("\n***welcome**")
        self.customer.registration()
      elif useroptions==2:
        username=input("\nenter the user full name")
        userpassword=input("\nenter the password")
        self.customer.login(username,userpassword)
        for i in self.customer.userlist:
             if (i.fullname ==username) &(i.password == userpassword):
                n=1
                while(n==1):

                   useroptions= int(input("\nPress 3 to order food :   \n Press 4 to view order history:  \nPress 5 to update profile "))
                   if useroptions==3:
                      self.customer.displayfooditems()
                   elif useroptions ==4:
                      self.customer.orderhistory()
                   elif useroptions ==5:
                      username=input("enter the user full name")
                      userpassword=input("enter the password")
                      self.customer.updateprofile(username ,userpassword)
                   n=int(input("if you want goto previous menu press 0 to continue as customer press 1"))
             else:
               print("you have entered wrong input")
               break


            
while True:
   choice = int(input("enter 1 for customer login/registration \nenter 2 for admin login "))
   mainobj=mainoperation()
   mainobj.execute(choice)





















































.















